                                                                                                                                                                                                                                                                                                                                                                                                                        -- ============================================
                                                                                                                                                                                                                                                                                                                                                                                                                        -- ELIMINAR esquema demo Barbería El Estilo
                                                                                                                                                                                                                                                                                                                                                                                                                        -- Idempotente: no falla si ya borraste parte del esquema
                                                                                                                                                                                                                                                                                                                                                                                                                        -- Supabase → SQL Editor → Run
                                                                                                                                                                                                                                                                                                                                                                                                                        -- ============================================

                                                                                                                                                                                                                                                                                                                                                                                                                        -- Vista
                                                                                                                                                                                                                                                                                                                                                                                                                        DROP VIEW IF EXISTS public.crm_dashboard;

                                                                                                                                                                                                                                                                                                                                                                                                                        -- Tablas (CASCADE quita triggers, policies e índices)
                                                                                                                                                                                                                                                                                                                                                                                                                        DROP TABLE IF EXISTS public.conversation_log CASCADE;
                                                                                                                                                                                                                                                                                                                                                                                                                        DROP TABLE IF EXISTS public.payments CASCADE;
                                                                                                                                                                                                                                                                                                                                                                                                                        DROP TABLE IF EXISTS public.appointments CASCADE;
                                                                                                                                                                                                                                                                                                                                                                                                                        DROP TABLE IF EXISTS public.clients CASCADE;
                                                                                                                                                                                                                                                                                                                                                                                                                        DROP TABLE IF EXISTS public.prospects CASCADE;
                                                                                                                                                                                                                                                                                                                                                                                                                        DROP TABLE IF EXISTS public.service_photos CASCADE;
                                                                                                                                                                                                                                                                                                                                                                                                                        DROP TABLE IF EXISTS public.services CASCADE;
                                                                                                                                                                                                                                                                                                                                                                                                                        DROP TABLE IF EXISTS public.barbers CASCADE;

                                                                                                                                                                                                                                                                                                                                                                                                                        -- ENUMs del demo
                                                                                                                                                                                                                                                                                                                                                                                                                        DROP TYPE IF EXISTS public.message_direction;
                                                                                                                                                                                                                                                                                                                                                                                                                        DROP TYPE IF EXISTS public.payment_status;
                                                                                                                                                                                                                                                                                                                                                                                                                        DROP TYPE IF EXISTS public.appointment_status;
                                                                                                                                                                                                                                                                                                                                                                                                                        DROP TYPE IF EXISTS public.contact_status;

                                                                                                                                                                                                                                                                                                                                                                                                                        -- Función del demo (comenta si otra cosa del proyecto la usa)
                                                                                                                                                                                                                                                                                                                                                                                                                        DROP FUNCTION IF EXISTS public.update_updated_at() CASCADE;

                                                                                                                                                                                                                                                                                                                                                                                                                        -- Verificación (debe devolver 0 filas):
                                                                                                                                                                                                                                                                                                                                                                                                                        SELECT tablename FROM pg_tables
                                                                                                                                                                                                                                                                                                                                                                                                                        WHERE schemaname = 'public'
                                                                                                                                                                                                                                                                                                                                                                                                                        AND tablename IN (
                                                                                                                                                                                                                                                                                                                                                                                                                            'barbers','services','service_photos','prospects','clients',
                                                                                                                                                                                                                                                                                                                                                                                                                            'appointments','payments','conversation_log'
                                                                                                                                                                                                                                                                                                                                                                                                                        );
